### ISSUE TITLE
Error on Win7 Pro 64-bit

### ISSUE THREAD

**Issue by xmr-eric** [ehmry/nim-monero#1]
Installed Nimble. Compiled binary. Running it makes it error though:

C:\nim-monero\monero\monero_vanity.exe test
gathering entropy and bruteforcing ‘test’ ...
Traceback (most recent call last)
monero_vanity.nim(93)   monero_vanity
monero_vanity.nim(86)   randInt
system.nim(2730)           sysFatal
Error: unhandled exception: cannot open: /dev/random [IOError]

Is there any dependencies that are required on Windows once I’ve successfully compiled the binary? That’s my suspicion of the problem.

**Comment by xmr-eric** [comment]
@ehmry ping

**Comment by ehmry** [comment]
Problem is that `/dev/random` is a Unix special file that doesn't exist on windows. I don't have a Windows host to test on, but I will look and see if there are any quick fixes.

**Comment by ehmry** [comment]
Fixed at #3.
